### ISSUE TITLE
Enhance KEP artifacts for human and automatic consumption

### ISSUE THREAD

**Issue by thockin** [kubernetes/enhancements#1544]
# Enhance KEP artifacts for human and automatic consumption
- KEP artifacts are difficult to navigate, but a few targeted changes can incrementally improve that.
- Kubernetes Enhancement Proposal: https://github.com/kubernetes/enhancements/pull/1545
- Primary contact (assignee): thockin
- Responsible SIGs: sig-architecture
- Enhancement target (which target equals to which milestone): N/A

**Comment by sftim** [comment]
@thockin did you mean to leave this issue open?

**Comment by justaugustus** [comment]
Yep, should've been closed.
/close
