### ISSUE TITLE
tracing

### ISSUE THREAD

**Issue by lashukla** [kubernetes/enhancements#2020]
# Enhancement Description
- One-line enhancement description (can be used as a release note):
- Kubernetes Enhancement Proposal: 
- Discussion Link: 
- Primary contact (assignee):
- Responsible SIGs:
- Enhancement target (which target equals to which milestone):
  - Alpha release target (x.y)
  - Beta release target (x.y)
  - Stable release target (x.y)

_Please keep this description up to date. This will help the Enhancement Team to track the evolution of the enhancement efficiently._

**Comment by mrbobbytables** [comment]
@lashukla as there is no further information in the issue, I'm going to go ahead and close it. If you have questions or comments please reopen with more information. 

Thanks!

/triage needs-information
/close
