### ISSUE TITLE
Allow Kubernetes liveness and readiness probe to support HTTPS on /health endpoints

### ISSUE THREAD

**Issue by patpatpat123** [kubernetes/enhancements#2089]
# Enhancement Description
- One-line enhancement description (can be used as a release note): Allow Kubernetes liveness and readiness probe to support HTTPS on /health endpoints

_Please keep this description up to date. This will help the Enhancement Team to track the evolution of the enhancement efficiently._

Hello Kubernetes Team,

I am here writing for an enhancement request, hope this makes sense and can be considered for a future release.

The current Kubernetes liveness probe and readiness probe are doing a great job checking app liveness and readiness.

However, for HTTP based probes, currently, it is only supported to do it over HTTP, not HTTPS.

More and more apps are required to be more secure, and having mTLS enabled even on /health endpoints.

While I fully understand there are workarounds (do a shell script based curl on the HTTPS endpoint, using service mesh, expose a separate /health endpoint over HTTP only), the ability to specify HTTPS (like we do today with HTTP) and the possibility to configure the certificates can be a very interesting feature in this world where apps are required to be more and more secure.

Thank you for your help, good day.

**Comment by ehashman** [comment]
Hi @patpatpat123,

Thanks for suggesting this! I would suggest you first file this as an issue against https://github.com/kubernetes/kubernetes. Once you've gauged community interest, you can then check with the SIG to see if they would be interested in implementing this. At that point, you can then start work on an enhancement. I am going to close this issue so you can go through that process :)
