### ISSUE TITLE
Migrate all KEPs to the new template

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/enhancements#2220]
This will facilitate strenghtening KEP validation

**Comment by wojtek-t** [comment]
The missing remaining itmes:

sig-apimachinery:
- /20200309-consistent-resource-versions-semantics   [requires creating an issue]

sig-cloud-provider:
- 3 cloud-provider KEPS (alibaba, baiducloud, huaweicloud)

sig-cluster-lifecycle:
- a bunch of stuff

sig-instrumentation:
- /1209-metrics-stability - [requires a bit of cleanup]

sig-network:
-  #2446 addresses most
- node-local-dns needs to be merged

**Comment by shekhar-rajak** [comment]
- I need clarification for "sig-cluster-lifecycle". I see directories and sub-directories. Should we just remove the sub-directories under the "sig-cluster-lifecycle" and follow the same pattern as others ? 

- Same for sig-instrumentation /1209-metrics-stability directory

**Comment by wojtek-t** [comment]
> I need clarification for "sig-cluster-lifecycle". I see directories and sub-directories. Should we just remove the sub-directories under the "sig-cluster-lifecycle" and follow the same pattern as others ?

No - this splits it to kind of "subprojects". We should basically put the new templates there, e.g. there will be
/sig-cluster-lifecycle/kubeadm/12345-kep-title/(first kep)
/sig-cluster-lifecycle/kubeadm/23466-kep-title/(second kep)

> Same for sig-instrumentation /1209-metrics-stability directory

Let's leave it for now - I will handle it later.

**Comment by wojtek-t** [comment]
@shekhar-rajak - if would be able to help with cluster-lifecycle, cloud-provider and api-machinery remaining ones it would be huge help - I will handle the remaining networking and instrumentaiton one.

**Comment by shekhar-rajak** [comment]
Sure @wojtek-t , I will work on it.

**Comment by neolit123** [comment]
one problem here is that all tracking issues get detached from the KEP locations. i can try updating the SIG CL tracking issues next week.

another problem is that KEP cross-ref links get broken.
i don't think we have many of these in SIG CL, but other SIGs might have them.

**Comment by wojtek-t** [comment]
> another problem is that KEP cross-ref links get broken.
i don't think we have many of these in SIG CL, but other SIGs might have them.

If needed, we can add symlinks to the new locations (there are a few for other SIGs).

**Comment by wojtek-t** [comment]
There are just few more:
```
time="2021-02-17T21:12:02+01:00" level=error msg="FAIL: /20200309-consistent-resource-versions-semantics/kep.yaml"
time="2021-02-17T21:12:02+01:00" level=error msg="FAIL: /providers/0020-cloud-provider-alibaba-cloud.md"
time="2021-02-17T21:12:02+01:00" level=error msg="FAIL: /providers/0022-cloud-provider-baiducloud.md"
time="2021-02-17T21:12:02+01:00" level=error msg="FAIL: /providers/20191206-cloud-provider-huaweicloud.md"
time="2021-02-17T21:12:02+01:00" level=error msg="FAIL: /1209-metrics-stability/20190404-kubernetes-control-plane-metrics-stability.md"
time="2021-02-17T21:12:02+01:00" level=error msg="FAIL: /1209-metrics-stability/20190605-metrics-stability-migration.md"
time="2021-02-17T21:12:02+01:00" level=error msg="FAIL: /1209-metrics-stability/20190605-metrics-validation-and-verification.md"
time="2021-02-17T21:12:02+01:00" level=error msg="FAIL: /1209-metrics-stability/20191028-metrics-stability-to-beta.md"
```

**Comment by wojtek-t** [comment]
Once #2524 and #2533 are merged, all KEPs will be migrated to the new template.
The only remaining thing I would like to do then is to strenghten validation a bit more.
