### ISSUE TITLE
Make kube-proxy service abstraction optional

### ISSUE THREAD

**Issue by shekhar-rajak** [kubernetes/enhancements#2447]
# Enhancement Description
- One-line enhancement description (can be used as a release note):

Make kube-proxy service abstraction optional

- Kubernetes Enhancement Proposal: 

In a cluster that has a service mesh a lot of the work being done by kube-proxy is redundant and wasted.
Specifically, services that are only reached via other services in the mesh will never use the service abstraction implemented by kube-proxy in iptables (or ipvs).
By informing the kube-proxy of this, we can lighten the work it is doing and the burden on its proxy backend.

- Discussion Link: 
- Primary contact (assignee): @bradhoekstra @thockin
- Responsible SIGs: sig-network
- Enhancement target (which target equals to which milestone):
  - Alpha release target (x.y):
  - Beta release target (x.y):
  - Stable release target (x.y):
- [ ] Alpha
  - [ ] KEP (`k/enhancements`) update PR(s):
  - [ ] Code (`k/k`) update PR(s):
  - [ ] Docs (`k/website`) update PR(s):

## Implementation History

- 2018-10-17 - This KEP is created
- 2018-11-12 - KEP updated, including approver/reviewer

_Please keep this description up to date. This will help the Enhancement Team to track the evolution of the enhancement efficiently._

**Comment by shekhar-rajak** [comment]
Migrating all the old template keps to new template : #2446

**Comment by thockin** [comment]
Implemented
