### ISSUE TITLE
Remove kube-proxy's automatic clean up logic

### ISSUE THREAD

**Issue by shekhar-rajak** [kubernetes/enhancements#2448]
# Enhancement Description
- One-line enhancement description (can be used as a release note):

Remove kube-proxy's automatic clean up logic

- Kubernetes Enhancement Proposal: 

Remove any clean up functionality in kube-proxy that is done automatically/implicitly.
More concretely, kube-proxy should only attempt to clean up its proxy rules when the `--cleanup` flag is set.

- Discussion Link: 
- Primary contact (assignee): @vllry @andrewsykim
- Responsible SIGs: sig-network
- Enhancement target (which target equals to which milestone):
  - Alpha release target (x.y):
  - Beta release target (x.y):
  - Stable release target (x.y):
- [ ] Alpha
  - [ ] KEP (`k/enhancements`) update PR(s):
  - [ ] Code (`k/k`) update PR(s):
  - [ ] Docs (`k/website`) update PR(s):

## Implementation History

* 2019-03-14: initial [bug report](https://github.com/kubernetes/kubernetes/issues/75360) was created where kube-proxy would flush iptable chains even when the proxy mode was iptables

_Please keep this description up to date. This will help the Enhancement Team to track the evolution of the enhancement efficiently._

**Comment by shekhar-rajak** [comment]
Migrating all the old template keps to new template : #2446

**Comment by thockin** [comment]
Implemented
