### ISSUE TITLE
Defining the Kubernetes release cadence

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/enhancements#2572]
# Enhancement Description
- One-line enhancement description (can be used as a release note): Defining the Kubernetes release cadence
- Kubernetes Enhancement Proposal: https://github.com/kubernetes/enhancements/pull/2567
- Discussion Link: https://github.com/kubernetes/sig-release/discussions/1290
- Primary contact (assignee): @justaugustus 
- Responsible SIG: SIG Release
- Participating SIGs: SIG Architecture, SIG Testing
- Enhancement target (which target equals to which milestone):
  - Alpha release target (x.y): 1.22
  - Beta release target (x.y): 1.23
  - Stable release target (x.y): 1.25
- [ ] Alpha
  - [ ] KEP (`k/enhancements`) update PR(s): https://github.com/kubernetes/enhancements/pull/2567
  - [ ] Code (`k/k`) update PR(s):
  - [ ] Docs (`k/website`) update PR(s):

_Please keep this description up to date. This will help the Enhancement Team to track the evolution of the enhancement efficiently._

/milestone v1.21
/stage alpha

**Comment by spiffxp** [comment]
/sig architecture testing
participating sigs
