### ISSUE TITLE
Enhancing the Console output of KUBECTL CLI

### ISSUE THREAD

**Issue by helper-uttam** [kubernetes/enhancements#3073]
### Enhancement Description
When I tried to delete a pod using **kubectl CLI** (`kubectl delete pod <POD_NAME>` ) then it firstly log `pod <POD_NAME> deleted` then in the background it is processing to delete the pod. 
**Expected Behavior:**
It should log something like `Deleting pod <POD_NAME>` then after deleting the pod it should log `pod <POD_NAME> deleted`.
- One-line enhancement description (can be used as a release note):
- Kubernetes Enhancement Proposal: 
- Discussion Link: 
- Primary contact (assignee):
- Responsible SIGs:
- Enhancement target (which target equals to which milestone):
  - Alpha release target (x.y):
  - Beta release target (x.y):
  - Stable release target (x.y):
- [ ] Alpha
  - [ ] KEP (`k/enhancements`) update PR(s):
  - [ ] Code (`k/k`) update PR(s):
  - [ ] Docs (`k/website`) update PR(s):

_Please keep this description up to date. This will help the Enhancement Team to track the evolution of the enhancement efficiently._

**Comment by pacoxu** [comment]
It sounds like a simple pull request to do. Should this be written as a KEP?
