### ISSUE TITLE
Increase Reliability Bar

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/enhancements#3138]
### Increase Reliability Bar

- One-line enhancement description:  Increase the Reliability Bar
- Kubernetes Enhancement Proposal: 
- Discussion Link: https://docs.google.com/document/d/1L6GdTC5REYUAqyb1Jx1goS9IEWCv1WRSxFxWqyaW_6w/edit#heading=h.afpvpo5e09y7
- Primary contact (assignee): @wojtek-t 
- Responsible SIGs: sig-architecture
- Enhancement target (which target equals to which milestone): process change, we will start in 1.24

_Please keep this description up to date. This will help the Enhancement Team to track the evolution of the enhancement efficiently._

**Comment by marcindulak** [comment]
:eyes:
