### ISSUE TITLE
Allow passing KUBECONFIG as base64 string

### ISSUE THREAD

**Issue by ilya-lesikov** [kubernetes/enhancements#3254]
### Enhancement Description

- One-line enhancement description (can be used as a release note): pass KUBECONFIG as base64 string
- Kubernetes Enhancement Proposal: TBD
- Discussion Link: https://github.com/kubernetes/kubernetes/issues/93346
- Primary contact (assignee): @ilya-lesikov
- Responsible SIGs: sig-cli
- Enhancement target (which target equals to which milestone):
  - Alpha release target (x.y): TBD
  - Beta release target (x.y): TBD
  - Stable release target (x.y): TBD
- [ ] Alpha
  - [ ] KEP (`k/enhancements`) update PR(s): TBD
  - [ ] Code (`k/k`) update PR(s): TBD
  - [ ] Docs (`k/website`) update PR(s): TBD

_Please keep this description up to date. This will help the Enhancement Team to track the evolution of the enhancement efficiently._

/sig cli

Related:
https://github.com/kubernetes/kubectl/issues/588 \
https://github.com/kubernetes/kubectl/pull/590 \
https://github.com/kubernetes/kubectl/issues/825

**Comment by soltysh** [comment]
Closing based on https://github.com/kubernetes/enhancements/pull/3255#issuecomment-1090509558

/close
