### ISSUE TITLE
Kubernetes swap support alpha feature -errors out  

### ISSUE THREAD

**Issue by martin2176** [kubernetes/enhancements#3514]
/sig node
/kind bug
 Azure (AKS) Kubernetes 1.24.3
 Followed instructions to enable the alpha feature for kubernetes swap.
POD spec
       resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "100m"

However starting a pod gives error (kubectl describe pod). I have tried all different combination of mem request and limit.
Removed the mem request and limit. Added same number for request and limit.
All gives out same error

  Warning  Failed     4s (x2 over 6s)   kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: open /sys/fs/cgroup/memory/kubepods/pod89b1a8ad-e180-4d32-9849-ad248a04f4f4/aksdebug/memory.memsw.limit_in_bytes: no such file or directory: unknown
  Normal   Pulled     4s                kubelet            Successfully pulled image "martin2176/aksdebugpod:v3" in 793.764549ms
  Warning  BackOff    2s (x2 over 3s)   kubelet            Back-off restarting failed container

Below are some relevant info:

kubectl get nodes
NAME                                STATUS   ROLES   AGE   VERSION
aks-npoolb2ms-73462207-vmss000000   Ready    agent   22m   v1.24.3

kubelet config

    "failSwapOn": false,
    "memorySwap": {
       "swapBehavior": "UnlimitedSwap"
        },
    "featureGates": {
        "CSIMigration": true,
        "CSIMigrationAzureDisk": true,
        "CSIMigrationAzureFile": true,
        "DelegateFSGroupToCSIDriver": true,
        "NodeSwap": true,
        "DisableAcceleratorUsageMetrics": false

Swap enabled and available on OS
root@aks-npoolb2ms-73462207-vmss000000:~# swapon -s
Filename                                Type            Size    Used    Priority
/mnt/swapfile                           file            14999996        0       -2

root@aks-npoolb2ms-73462207-vmss000000:/etc# cat os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"

**Comment by kikisdeliveryservice** [comment]
@martin2176 this looks like a bug report. Please open in https://github.com/kubernetes/kubernetes/issues and be sure to label the issue with the correct sig and type.

Closing this as it is not an enhancement.

Thanks!
