### ISSUE TITLE
Cgroup v2 and kubelet's memoryThrottlingFactor in K3s

### ISSUE THREAD

**Issue by MyCodel** [kubernetes/enhancements#3662]
I turned on Cgroup v2 and configured kubelet's memoryThrottlingFactor, but it doesn't seem to take effect, memory.min and memory.low is always 0, memory.high is always max, memory.max memory.max is set correctly. Am I missing some configurations?

My configurations:
1、Pod:
      resources:
        limits:
          cpu: 128m
          memory: 512Mi
        requests:
          cpu: 64m
          memory: 256Mi

2、Cgroup v2：
stat -fc %T /sys/fs/cgroup/
cgroup2fs

3、kubelet：
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
memoryThrottlingFactor: 0.8

cat memory.high
max
cat memory.low
0
cat memory.min
0
cat memory.max
536870912

https://github.com/kubernetes/enhancements/issues/3662#tasklist-block-e578547c-773c-4f33-8524-22c767bd3c7f

**Comment by aojea** [comment]
This repo is used to propose features to Kubernetes, is not used to report issues

Also, K3S has its own project, better to report there

/close
