### ISSUE TITLE
In the KEP template better clarify the difference of integration vs. e2e tests

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/enhancements#3860]
As discussed today a [SIG Arch: Production Readiness Office Hours](https://docs.google.com/document/d/10QkXwiZfBL7wBKHHFslooXvGDKHA75jkkgiIXuKFryM/edit#) the sections Integration tests and e2e tests are often confused - same text placed in both or one of the sections got ignored.

Integration tests are likely referring to the tests under the folder `test/integration` in k/k. This would be great to clarify it in PRR template.

/kind cleanup
/assign @deads2k

**Comment by kikisdeliveryservice** [comment]
There was a similar bug open [here](https://github.com/kubernetes/enhancements/issues/3827#issue-1568807579). Tracking integration test issues via this bug for clarity.

cc: @MikeSpreitzer
