### ISSUE TITLE
`ContainerStatus` image reference field

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/enhancements#4516]
### Enhancement Description

- One-line enhancement description (can be used as a release note): Adding the image reference (digest) to the existing [`ContainerStatus`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#containerstatus-v1-core) API
- Kubernetes Enhancement Proposal: None
- Discussion Link: https://groups.google.com/g/kubernetes-sig-node/c/hbfOUA2VGOI/m/4QKR4ejEAQAJ
- Primary contact (assignee): @saschagrunert 
- Responsible SIGs: Node
- Enhancement target (which target equals to which milestone): v1.31
  - Alpha release target (x.y): v1.31
  - Beta release target (x.y):
  - Stable release target (x.y):
- [ ] Alpha
  - [ ] KEP (`k/enhancements`) update PR(s):
  - [ ] Code (`k/k`) update PR(s):
  - [ ] Docs (`k/website`) update PR(s):

_Please keep this description up to date. This will help the Enhancement Team to track the evolution of the enhancement efficiently._

Refers to https://github.com/kubernetes/kubernetes/issues/46255

cc @mrunalp @haircommander @kubernetes/sig-node-feature-requests

**Comment by mrunalp** [comment]
cc: @mikebrow

**Comment by saschagrunert** [comment]
Closing, we will solve this issue via the CRI.
