### ISSUE TITLE
Dynamics informers for custom CRDS

### ISSUE THREAD

**Issue by hardikpaloda123** [kubernetes/enhancements#4594]
### Enhancement Description

- Dynamics informers for custom CRDS (can be used as a release note):
- Kubernetes Enhancement Proposal: In day to day life we use informers to observe the standard k8s entity. but it will be useful to have  the dynamics informers as well which can take inout for custom crds and observe them.
- Discussion Link: 
- Primary contact (assignee): hardikpaloda123
- Responsible SIGs:
- Enhancement target (which target equals to which milestone):
  - Alpha release target (x.y):
  - Beta release target (x.y):
  - Stable release target (x.y):
- [ ] Alpha
  - [ ] KEP (`k/enhancements`) update PR(s):
  - [ ] Code (`k/k`) update PR(s):
  - [ ] Docs (`k/website`) update PR(s):

_Please keep this description up to date. This will help the Enhancement Team to track the evolution of the enhancement efficiently._

**Comment by SOF3** [comment]
isn't this basically k8s.io/client-go/dynamic?
