### ISSUE TITLE
Support Out-of-Tree Photon Cloud Provider 

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/enhancements#674]
# Enhancement Description
- One-line enhancement description (can be used as a release note):
Support Out-of-Tree Photon Cloud Provider by running the cloud-controller-manager
- Primary contact (assignee):
@andrewsykim 
- Responsible SIGs:
SIG Cloud Provider
- Reviewer(s) - (for LGTM) recommend having 2+ reviewers (at least one from code-area OWNERS file) agreed to review. Reviewers from multiple companies preferred:
@andrewsykim 
- Approver (likely from SIG/area to which enhancement belongs):
@andrewsykim 
- Enhancement target (which target equals to which milestone):
  - Alpha release target (x.y)
  - Beta release target (x.y)
  - Stable release target (x.y)

Ref https://github.com/kubernetes/enhancements/issues/88 

/sig cloud-provider

**Comment by frapposelli** [comment]
Hey @andrewsykim the `photon` cloud provider is deprecated and will not be supported out of tree, there's an open PR to remove the code from k/k kubernetes/kubernetes#72178
